// <auto-generated />
namespace MultiThreadingDemo.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CollectiveInformationJson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CollectiveInformationJson));
        
        string IMigrationMetadata.Id
        {
            get { return "202203032228522_CollectiveInformationJson"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
